### ISSUE TITLE
Finish email form (frontend)

### ISSUE THREAD

**Issue by ghost** [LiamRahav/InFuture#3]
Finish the email form (so it's functional and beautiful), in both frontend and backend.

**Comment by unitedjaymo** [comment]
I redid the email form - check out the latest version of it at http://infuture.io/
Closing the issue, if anyone wants a redesign of the form please reopen the issue

**Comment by ghost** [comment]
I redid the email form - check out the latest version of it at http://infuture.io/
Closing the issue, if anyone wants a redesign of the form please reopen the issue

**Comment by ghost** [comment]
The form is not really responsive - to be fixed.
